# docker-compose.yml
version: '3.8'

services:
  app:
    container_name: eng-dictionary-bot
    image: eng-dictionary-bot
    build: .
    ports:
      - ${PORT}:${PORT}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s
